# Generated by Django 5.0.3 on 2024-03-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mode',
            field=models.CharField(choices=[('COD', 'Cash ON Delivery'), ('ON', 'Online')], max_length=20, null=True),
        ),
    ]
